run:
  deadline: 1h
  tests: true

linters:
  enable:
    - gocyclo
    - gofmt
    - golint

linters-settings:
  gocyclo:
    min-complexity: 11

  gofmt:
    simplify: true

  golint:
    min-confidence: 0
