run:
  deadline: 5m
  modules-download-mode: vendor
  tests: true

linters:
  enable-all: true
  disable:
    - gas

linters-settings:
  gocyclo:
    min-complexity: 11
  gofmt:
    simplify: true
  golint:
    min-confidence: 0
