sudo: false

language: go

go:
  - 1.11.x

env:
  - GO111MODULE=on

git:
  depth: 1

notifications:
  email: false

install: true

before_script:
  - go install -tags tools github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - golangci-lint run
