language: go

go:
  - 1.x

notifications:
  email: false

install: true

before_script:
  - cd vendor/github.com/golang/lint/golint
  - go install
  - cd -
  - cd vendor/honnef.co/go/tools/cmd/megacheck
  - go install
  - cd -

script:
  - test -z $(gofmt -s -l *.go)
  - go vet ./...
  - megacheck ./...
  - golint -set_exit_status $(find . -iname '*.go' | grep -v /vendor/)
