sudo: false

language: go

go:
  - 1.x

git:
  depth: 1

notifications:
  email: false

install: true

before_script:
  - go install ./vendor/github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - golangci-lint run
