language: go

go:
  - 1.x

notifications:
  email: false

before_script:
  - go get github.com/golang/lint/golint
  - go get honnef.co/go/tools/cmd/megacheck

script:
  - test -z $(gofmt -s -l *.go)
  - go vet ./...
  - megacheck ./...
  - golint -set_exit_status ./...
