required = [
  "github.com/golangci/golangci-lint/cmd/golangci-lint",
]

[[constraint]]
  name = "github.com/golangci/golangci-lint"
  version = "^1.7.0"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
