version: 2.1

executors:
  rust-container:
    docker:
      - image: rust:1-slim
    working_directory: /usr/src/update-shell-utils

jobs:
  check:
    executor:
      name: rust-container
    steps:
      - checkout
      - run: cargo check --all --all-features --all-targets --locked

  fmt:
    executor:
      name: rust-container
    steps:
      - checkout
      - run: rustup component add rustfmt
      - run: cargo fmt --all -- --check

  lint:
    executor:
      name: rust-container
    steps:
      - checkout
      - run: rustup component add clippy
      - run: cargo clippy --all-features --all-targets --locked -- --deny clippy::all --deny clippy::cargo

  test:
    executor:
      name: rust-container
    steps:
      - checkout
      - run: cargo test --all --all-features --all-targets --locked

workflows:
  version: 2
  do_all_the_things:
    jobs:
      - check
      - fmt:
          requires:
            - check
      - lint:
          requires:
            - check
      - test:
          requires:
            - check
