version: 2.1
jobs:
  build:
    docker:
      - image: golang:1.11
    environment:
      GO111MODULE: 'on'
    working_directory: /go/src/github.com/y0ssar1an/update-shell-utils
    steps:
      - checkout
      - run: go install -mod vendor github.com/y0ssar1an/update-shell-utils/vendor/github.com/golangci/golangci-lint/cmd/golangci-lint
      - run: golangci-lint run
